### PR TITLE
https://github.com/Marc-pi/mobileapi/issues/1 Add fulltext index for …

### PR DESCRIPTION
**Pull request by Marc-pi**
…mobileapi search

### CODE REVIEW

**Comment by voltan** [comment]
this change work on all servers? if mysql not last version or do not support FULLTEXT index?

**Comment by Marc-pi** [comment]
fulltext since  3.23.23.

**Comment by Marc-pi** [comment]
now we are 5.7 :-)

**Comment by Marc-pi** [comment]
and it is time to move to InnoDB

**Comment by voltan** [comment]
I talk about 12 different servers and I dont have access to update all of them, most of servers have mysql 5.5 and one of them have 5.6

**Pull request merged**
