### PR TITLE
add sticky for article-story, add auto thumb height

### PR DESCRIPTION
**Pull request by Marc-pi**
we will move those lib to core as soon as we test Pi 2.5. for now we keep them in each modules

### CODE REVIEW

**Comment by voltan** [comment]
Can we add jquery-match-height and hc-sticky on core libs ? and perhaps partia templates

**Comment by Marc-pi** [comment]
yes, we will do as soon as we test Pi 2.5

**Comment by Marc-pi** [comment]
betw we do not have access to pi-engine/guide !!!

**Comment by Marc-pi** [comment]
taiwen seem to forgot to renew GH fees

**Comment by voltan** [comment]
do you have backup from last changes? perhaps it better to set your form as main repo and we can form it on our acounts

**Comment by Marc-pi** [comment]
the problem are the issues that are important, i cannot retrieve them 
i'll contact taiwen by mail and through instagram (cc @taiwen )

**Comment by voltan** [comment]
perhaps you can access to repo by contact to github , you can have access to create new repo on pi-engine organization , than you can make payment for it .

generaly perhaps it possible to move guide repo to pi module , than you can make payment for this organization

**Comment by voltan** [comment]
I check , its possible from here https://github.com/pi-engine/guide/settings

**Comment by Marc-pi** [comment]
yes, i saw, the question is about retrieving history and issues (actually those are disabled)
the classic way is to transfer during the normal state (current fee period active)
i've send an email to github to know more, i'm waiting for their answer

**Comment by voltan** [comment]
I think every things transfer

**Comment by Marc-pi** [comment]
even if disabled?

**Comment by voltan** [comment]
I think yes

**Pull request merged**
